name: SSH deploy on push
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Execute server-side script
        run: |      
          chmod +x migrate.sh

      - name: Install PHP dependencies with Composer
        run: composer install --optimize-autoloader --no-dev
      
      - name: rsync deploy
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: "-avzr --delete --exclude='.env' --exclude='node_modules' --exclude='.git' --exclude='.github' --exclude='.htaccess' --exclude='public/.htaccess' --exclude='public/images/landings'"
          path: .
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.REMOTE_KEY }}
          remote_path: ${{ secrets.REMOTE_PATH }}

      - name: Set execute permissions on migrate.sh
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.REMOTE_KEY }} ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "chmod +x ${{ secrets.REMOTE_PATH }}/migrate.sh"
      
      - name: Deploy to remote server
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.REMOTE_KEY }} ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "cd ${{ secrets.REMOTE_PATH }} && ./migrate.sh"